name: Schedule
on:
  schedule:
    - cron:  '02 * * * *'
jobs:
  Request:
    name: Start Request
    runs-on: ubuntu-latest
    steps:
      - run: echo "Begin"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          yarn install
          yarn start
      - run: echo "End"
